version: '3'

services:
  docker-mysql:
    image: 'mysql:8.0'
    container_name: docker-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: ./
    container_name: my_cloud
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/cloud_storage_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT=25000
    depends_on:
      - docker-mysql