version: '3'

services:
  docker-mysql:
    image: 'mysql:8.0'
    container_name: docker-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3306:3306"

  app:
    image: openjdk:11-jre
    container_name: my_cloud
    ports:
      - "8081:8081"
    volumes:
      - .:/code
    command:
      - java -jar /code/target/cloud_storage-0.0.1-SNAPSHOT.jar
    depends_on:
      - docker-mysql